# symworx/Cargo.toml
# Copyright (C) 2026 cSYMd, All rights reserved.

[workspace]
resolver = "2"
members = [
    # "crates/backend",
    "crates/symworx-biosym",
    "crates/symworx-core",
    "crates/symworx-dynamics",
    "crates/symworx-io",
    "crates/symworx-loadsym",
    "crates/symworx-math",
    "crates/symworx-runsym",
    "crates/symworx-signal",
    "crates/symworx-stats",
    "bindings/python",
]

[workspace.package]
version    = "0.1.0"
edition    = "2024"
license    = "MPL-2.0"
repository = "https://github.com/csymd/symworx"
authors    = ["ntberry nate-berry@outlook.com"]

[workspace.dependencies]
csv            = { version = "1.3" }
ndarray        = { version = "0.15", features = ["std"] }
ndarray-linalg = { version = "0.16", features = ["openblas"] }
parquet        = { version = "51.0" }
rand           = { version = "0.9" }
rand_distr     = { version = "0.5" }
tokio          = { version = "1", features = ["full"] }