# Copyright (C) 2026 cSYMd, All rights reserved.

[package]
name = "symworx-backend"
version          = { workspace = true }
edition          = { workspace = true }
license          = { workspace = true }
repository       = { workspace = true }
description      = "Backend utilities -- part of the symworx-core crate"

[dependencies]
tokio = { workspace = true }