# symworx/crates/symworx-biosym/Cargo.toml
# Copyright (C) 2026 cSYMd, All rights reserved.

[package]
name = "symworx-biosym"
version          = { workspace = true }
edition          = { workspace = true }
license          = { workspace = true }
repository       = { workspace = true }
description      = "Biological (phys, mech, cpg) modeling tools and resources"

[dependencies]
ndarray      = { workspace = true }
# rand and rand_distr kept minimal / optional for core biomechanics
# rand         = { workspace = true }
# rand_distr   = { workspace = true }

symworx-core = { path = "../symworx-core" }
symworx-math = { path = "../symworx-math" }
