[package]
name = "symworx-python"
version.workspace = true
edition.workspace = true

[lib]
name       = "symworx"
crate-type = ["cdylib"]

[dependencies]
pyo3            = { workspace = true }
ndarray         = { workspace = true }
ndarray-linalg  = { workspace = true }
numpy           = { version = "0.23" }

symworx-core    = { path = "../../crates/symworx-core", version = "0.1" }
symworx-biosym  = { path = "../../crates/symworx-biosym", version = "0.1" }
symworx-loadsym = { path = "../../crates/symworx-loadsym", version = "0.1" }