# Copyright (C) 2026 cSYMd, All rights reserved.

[package]
name = "symworx-loadsym"
version          = { workspace = true }
edition          = { workspace = true }
license          = { workspace = true }
repository       = { workspace = true }
description      = "Load and periodization modeling"

[dependencies]
ndarray         = { version = "0.15", features = ["std"] }
# numpy           = { version = "0.21" }

symworx-core    = { path = "../symworx-core" }
