# Copyright (C) 2026 cSYMd, All rights reserved.

[package]
name = "symworx-core"
version          = { workspace = true }
edition          = { workspace = true }
license          = { workspace = true }
repository       = { workspace = true }
description      = "Core dependencies bunded togther for convenience"

[dependencies]
symworx-backend  = { path = "../symworx-backend" }
symworx-dynamics = { path = "../symworx-dynamics" }
symworx-error    = { path = "../symworx-error" }
symworx-io       = { path = "../symworx-io" }
symworx-math     = { path = "../symworx-math" }
symworx-signal   = { path = "../symworx-signal" }
symworx-stats    = { path = "../symworx-stats" }