# symworx/crates/symworx-core/Cargo.toml
# Copyright (C) 2026 cSYMd, All rights reserved.

[package]
name = "symworx-core"
version.workspace = true
edition.workspace = true

[dependencies]
symworx_backend  = { path = "../symworx-backend" }
symworx_dynamics = { path = "../symworx-dynamics" }
symworx_io       = { path = "../symworx-io" }
symworx_math     = { path = "../symworx-math" }
symworx_signal   = { path = "../symworx-signal" }
symworx_stats    = { path = "../symworx-stats" }