# Copyright (C) 2026 SymWorx, All rights reserved.

[package]
name = "symworx-signal"
version          = { workspace = true }
edition          = { workspace = true }
license          = { workspace = true }
repository       = { workspace = true }
description      = "Signal-related tools and resources -- part of the symworx-core crate"

[dependencies]
ndarray        = { workspace = true }
ndarray-linalg = { workspace = true }
num-complex    = { workspace = true }
rustfft        = { workspace = true }

symworx-stats  = { path = "../symworx-stats" }

[lints]
workspace = true