# Copyright (C) 2026 SymWorx, All rights reserved.

[package]
name = "symworx-signal"
version          = { workspace = true }
edition          = { workspace = true }
license          = { workspace = true }
repository       = { workspace = true }
authors          = { workspace = true }
description      = "Signal processing tools and resources (filters, peaks, sparse sensing, interpolation, resampling)"
keywords = ["signal-processing", "filters", "peaks", "time-series", "biosignals", "compressed-sensing"]
categories = ["science"]

[dependencies]
ndarray        = { workspace = true }
ndarray-linalg = { workspace = true }
num-complex    = { workspace = true }
rustfft        = { workspace = true }

symworx-stats  = { workspace = true }

[dev-dependencies]
symworx-math = { workspace = true }

[lints]
workspace = true