# Copyright (C) 2026 SymWorx, All rights reserved.

[package]
name = "symworx-io"
version          = { workspace = true }
edition          = { workspace = true }
license          = { workspace = true }
repository       = { workspace = true }
description      = "I/O utilities -- part of the symworx-core crate"

[dependencies]
csv          = { workspace = true }
ndarray      = { workspace = true }
parquet      = { workspace = true }

symworx-error = { path = "../symworx-error" }

[lints]
workspace = true
