# Copyright (C) 2026 SymWorx, All rights reserved.

[package]
name = "symworx-error"
version          = { workspace = true }
edition          = { workspace = true }
license          = { workspace = true }
repository       = { workspace = true }

[dependencies]
csv         = { workspace = true }
parquet     = { workspace = true }
thiserror   = { workspace = true }
