# Copyright (c) 2026 PalEm Dynamics LLC
# Licensed under the Apache License, Version 2.0.

[package]
name = "symworx-error"
version          = { workspace = true }
edition          = { workspace = true }
license          = { workspace = true }
repository       = { workspace = true }
authors          = { workspace = true }
description      = "Error types for the SymWorx ecosystem"
keywords = ["error", "utilities"]
categories = ["development-tools"]

[dependencies]
csv         = { workspace = true }
parquet     = { workspace = true, optional = true }
thiserror   = { workspace = true }

[features]
default = []
parquet = ["dep:parquet"]
