# symworx/crates/symworx-stats/Cargo.toml
# Copyright (C) 2026 cSYMd, All rights reserved.

[package]
name = "symworx-stats"
version          = { workspace = true }
edition          = { workspace = true }
license          = { workspace = true }
repository       = { workspace = true }
description      = "Statistical tools and resources -- part of the symworx-core crate"

[dependencies]
ndarray        = { workspace = true }
ndarray-linalg = { workspace = true }
rustfft        = { workspace = true }

symworx-math   = { path = "../symworx-math" }